// Hand-rolled tx builders. In production these are generated by
// `buf generate` against `genesis/chain/proto/`. For the v0 frontend
// scaffold we encode the JSON shape the keeper expects and let the SDK's
// amino JSON path sign it.

import type { OfflineSigner } from "@cosmjs/proto-signing";
import { SigningStargateClient, GasPrice } from "@cosmjs/stargate";
import { agenticChain } from "./chain";

export interface SwapArgs {
  swapper: string;
  poolId: bigint;
  amountIn: { denom: string; amount: string };
  denomOut: string;
  minAmountOut: string; // string-encoded sdk.Int
}

const RPC = agenticChain.apis!.rpc![0].address;

export async function getClient(signer: OfflineSigner) {
  return SigningStargateClient.connectWithSigner(RPC, signer, {
    gasPrice: GasPrice.fromString("0.0005ugen"),
  });
}

// Encode `MsgSwap` from x/agenticdex. The typeUrl mirrors the protobuf
// package path declared in `genesis/chain/proto/agenticdex/v1/tx.proto`
// (forthcoming — until then the keeper's JSON unmarshalling path handles
// the same wire shape).
export function encodeSwap(args: SwapArgs) {
  return {
    typeUrl: "/agenticdex.v1.MsgSwap",
    value: {
      swapper: args.swapper,
      pool_id: args.poolId.toString(),
      amount_in: args.amountIn,
      denom_out: args.denomOut,
      min_amount_out: args.minAmountOut,
    },
  };
}

export async function swap(signer: OfflineSigner, args: SwapArgs) {
  const client = await getClient(signer);
  const accounts = await signer.getAccounts();
  return client.signAndBroadcast(
    accounts[0].address,
    [encodeSwap(args)],
    "auto",
    "AGENTIC DEX swap"
  );
}
