// Hand-rolled Msg types. In a production build these are generated by
// `buf generate` from `proto/agentic/v1/tx.proto`; the hand-written
// versions here let the package compile in this scaffold before the proto
// pipeline is wired up, and they document the exact wire shape we expect.
package types

import (
	"errors"
	"fmt"

	"cosmossdk.io/math"
	sdk "github.com/cosmos/cosmos-sdk/types"
)

// ───────────────────────── MsgRegisterAgent ─────────────────────────

type MsgRegisterAgent struct {
	Operator string   `json:"operator"`
	Moniker  string   `json:"moniker"`
	Endpoint string   `json:"endpoint"`
	Stake    math.Int `json:"stake"`
}

func (m MsgRegisterAgent) ValidateBasic() error {
	if _, err := sdk.AccAddressFromBech32(m.Operator); err != nil {
		return fmt.Errorf("invalid operator: %w", err)
	}
	if m.Moniker == "" {
		return errors.New("moniker required")
	}
	if !m.Stake.IsPositive() {
		return errors.New("stake must be positive")
	}
	return nil
}

// ───────────────────────── MsgCreateTask ─────────────────────────

type MsgCreateTask struct {
	Requester string   `json:"requester"`
	Agent     string   `json:"agent"`
	Bounty    math.Int `json:"bounty"`
	Spec      string   `json:"spec"`
}

func (m MsgCreateTask) ValidateBasic() error {
	if _, err := sdk.AccAddressFromBech32(m.Requester); err != nil {
		return fmt.Errorf("invalid requester: %w", err)
	}
	if _, err := sdk.AccAddressFromBech32(m.Agent); err != nil {
		return fmt.Errorf("invalid agent: %w", err)
	}
	if !m.Bounty.IsPositive() {
		return errors.New("bounty must be positive")
	}
	if len(m.Spec) == 0 || len(m.Spec) > 4096 {
		return errors.New("spec length must be 1..4096")
	}
	return nil
}

// ───────────────────────── MsgSubmitResponse ─────────────────────────

type MsgSubmitResponse struct {
	Agent       string `json:"agent"`
	TaskID      uint64 `json:"task_id"`
	ResponseCID string `json:"response_cid"`
}

func (m MsgSubmitResponse) ValidateBasic() error {
	if _, err := sdk.AccAddressFromBech32(m.Agent); err != nil {
		return fmt.Errorf("invalid agent: %w", err)
	}
	if m.TaskID == 0 {
		return errors.New("task_id required")
	}
	if len(m.ResponseCID) < 16 || len(m.ResponseCID) > 256 {
		return errors.New("response_cid length must be 16..256 (e.g. IPFS CIDv1)")
	}
	return nil
}

// ───────────────────────── MsgSettleTask ─────────────────────────

type MsgSettleTask struct {
	Requester string `json:"requester"`
	TaskID    uint64 `json:"task_id"`
}

func (m MsgSettleTask) ValidateBasic() error {
	if _, err := sdk.AccAddressFromBech32(m.Requester); err != nil {
		return fmt.Errorf("invalid requester: %w", err)
	}
	if m.TaskID == 0 {
		return errors.New("task_id required")
	}
	return nil
}

// ───────────────────────── MsgSubmitFraudProof ─────────────────────────

type MsgSubmitFraudProof struct {
	Attestor string `json:"attestor"`
	TaskID   uint64 `json:"task_id"`
	Evidence string `json:"evidence"`
}

func (m MsgSubmitFraudProof) ValidateBasic() error {
	if _, err := sdk.AccAddressFromBech32(m.Attestor); err != nil {
		return fmt.Errorf("invalid attestor: %w", err)
	}
	if m.TaskID == 0 {
		return errors.New("task_id required")
	}
	if len(m.Evidence) == 0 || len(m.Evidence) > 1024 {
		return errors.New("evidence length must be 1..1024")
	}
	return nil
}

// ───────────────────────── MsgUpdateParams ─────────────────────────

type MsgUpdateParams struct {
	Authority string `json:"authority"`
	Params    Params `json:"params"`
}

func (m MsgUpdateParams) ValidateBasic() error {
	if _, err := sdk.AccAddressFromBech32(m.Authority); err != nil {
		return fmt.Errorf("invalid authority: %w", err)
	}
	return m.Params.Validate()
}

// Response types are kept empty for v0; tx receipts carry settlement data
// through events instead. Adding fields here is a non-breaking change.

type MsgRegisterAgentResponse    struct{}
type MsgCreateTaskResponse       struct{ TaskID uint64 `json:"task_id"` }
type MsgSubmitResponseResponse   struct{}
type MsgSettleTaskResponse       struct{}
type MsgSubmitFraudProofResponse struct{}
type MsgUpdateParamsResponse     struct{}
